server:
  port:  ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movie-service
          uri: lb://api-movie
          predicates:
            - Path=/movies/**
        - id: catalog-service
          uri: lb://api-catalog
          predicates:
            - Path=/catalog/**
        #- id: mssmargins
         # uri: lb://api-margins
         # predicates:
          #  - Path=/calculate/**

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
